spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  redis:
    host: 192.168.1.104
    port: 6379
  mvc:
    static-path-pattern: /static/**
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx8967a7421853af6a
  mpAppSecret: 7fad0591ee96c48323afa293f281b59f
