spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nanhang
    password: hang2212
    url: jdbc:mysql://localhost:3306/wechatpay?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
server:
  servlet:
    context-path: /sell
